drop table if exists member CASCADE;
create table member
(
    id bigint generated by default as identity,
    name varchar(15),
    password varchar(15),

    fav_soccer boolean,
    fav_futsal boolean,
    fav_baseball boolean,
    fav_basketball boolean,
    fav_badminton boolean,
    fav_cycle boolean,

    primary key (id)
);