drop table if exists matchingdto CASCADE;
create table matchingdto
(
    id bigint generated by default as identity,
    user_index bigint not null,
    open_match_id bigint not null,

    primary key (id)
);