drop table if exists open_matchdto CASCADE;
create table open_matchdto
(
    id bigint generated by default as identity,
    open_user_id varchar(20) not null,
    open_match_pw int,
    open_time datetime2,
    subject varchar(50) not null,
    article text,
    sport_type varchar(20),
    personnel int,
    play_date_time datetime2,
    lat double,
    lng double,

    primary key (id)
);