drop table if exists profile CASCADE;
create table profile(
    idx bigint generated by default as identity,

    user_id varchar(15),
    nickname varchar(20) not null,
    image text,
    introduce text,
    region text,

    fav_mon boolean,
    fav_tue boolean,
    fav_wed boolean,
    fav_thu boolean,
    fav_fri boolean,
    fav_sat boolean,
    fav_sun boolean,

    fav_soccer boolean,
    fav_futsal boolean,
    fav_baseball boolean,
    fav_basketball boolean,
    fav_badminton boolean,
    fav_cycle boolean,

    primary key (idx),
    unique (user_id)
);