drop table if exists profile CASCADE;
create table profile(
    idx bigint generated by default as identity,

    nickname varchar(20) not null,
    image text,
    introduce text,
    region text,
    available_date text,

    fav_soccer boolean,
    fav_futsal boolean,
    fav_baseball boolean,
    fav_basketball boolean,
    fav_badminton boolean,
    fav_cycle boolean,
);