drop table if exists refresh_token CASCADE;
create table refresh_token
(
    idx                         bigint not null      generated by default as identity,
    access_token                text        not null,
    refresh_token               text        not null,
    refresh_token_expiration_at datetime default null,
    user_id                     varchar(15) not null,

    primary key (idx),
    unique (user_id)
);